version: "3.8"

services:
  app:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

  posgtres:
    image: postgres
    volumes:
      - todo-postgres-data:/var/lib/postgresql   
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: todos
      POSTGRES_USER: postgres
      
volumes:
  todo-mysql-data:
  todo-postgres-data: